<?php
/**
 * includes/items/items.php
 *
 * Categories and items.
 */

/**
 * Categories and items
 *
 * @var array
 */
$ci = [
  'creation' => [
    'title' => 'Posterstellung',
    'symbol' => 'f5ae',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://pr0texter.pimmelmannjones.com',
        'thumb' => 'pr0texter',
        'name' => 'pr0texter',
        'author' => 'PimmelmannJones',
        'description' => 'Tool zur einfachen Erstellung von Textposts',
      ],
      [
        'url' => 'https://pr0gramm.com/upload-info',
        'thumb' => 'eckdaten',
        'name' => 'Eckdaten',
        'author' => 'pr0gramm',
        'description' => 'Eckdaten, Farben, Bilder für Textposts',
      ],
      [
        'url' => 'https://pr0gramm.com/new/3295515',
        'thumb' => 'thumbnails',
        'name' => 'Thumbnail mit Rahmen',
        'author' => 'Retrowinger',
        'description' => 'Anleitung für schöne Thumbnails mit Rahmen',
      ],
      [
        'url' => 'https://retropr0.github.io/pr0p0st/html/',
        'thumb' => 'pr0p0st',
        'name' => 'pr0p0st',
        'author' => 'retro',
        'description' => 'Tool zur Erstellung von Textposts',
      ],
      [
        'url' => 'https://pr0gramm.com/new/1947058',
        'thumb' => 'tts',
        'name' => 'text2speech Tutorial',
        'author' => 'qbl',
        'description' => 'Text2Speech / Computerstimme für OC-Videos',
      ],
      [
        'url' => 'https://pr0gramm.com/new/3156775',
        'thumb' => 'scribus',
        'name' => 'Scribus Tutorial',
        'author' => 'Retrowinger',
        'description' => 'Anleitung zum Erstellen von Posts mittels Scribus',
      ],
      [
        'url' => 'https://github.com/MurchGit/pr0mplate',
        'thumb' => 'affinityTemplate',
        'name' => 'Affinity Template',
        'author' => 'Murch',
        'description' => 'Template zum Erstellen von Posts mittels Affinity',
      ],
      [
        'url' => 'https://pr0gramm.com/new/6843796',
        'thumb' => 'inkscapeTutorial',
        'name' => 'Inkscape Tutorial',
        'author' => 'Analchist',
        'description' => 'Video-Tutorial zur Erstellung eingerahmter Vorschaubilder und Text-Hochlads via Inkscape',
      ],
    ],
  ],
  'upload' => [
    'title' => 'Hochladen',
    'symbol' => 'f0ee',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://pr0verter.de/',
        'thumb' => 'pr0verter',
        'name' => 'pr0verter',
        'author' => 'PimmelmannJones',
        'description' => 'Konvertiere deine Videos direkt passend fürs pr0!',
      ],
      [
        'url' => 'https://rep0st.rene8888.at/',
        'thumb' => 'rep0st',
        'name' => 'rep0st',
        'author' => 'Rene8888',
        'description' => 'Repost Suche',
      ],
      [
        'url' => 'https://pr0gramm.com/new/3322321',
        'thumb' => 'pr0verter_offline',
        'name' => 'pr0verter Offline',
        'author' => 'Pennypacker',
        'description' => 'Der pr0verter als Offline-Version',
      ],
    ],
  ],
  'official' => [
    'title' => 'Offizielles',
    'symbol' => 'f120',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://app.pr0gramm.com/',
        'thumb' => 'app',
        'name' => 'pr0gramm Android App',
        'author' => 'Mopsalarm',
        'description' => 'Die offizielle pr0gramm Android App',
      ],
      [
        'url' => 'https://pr0mart.com',
        'thumb' => 'pr0mart',
        'name' => 'pr0mart',
        'author' => 'pr0mart',
        'description' => 'Der offizielle pr0gramm Merchandise Shop',
      ],
      [
        'url' => 'https://z0cken.com/',
        'thumb' => 'z0cken',
        'name' => 'z0cken.com',
        'author' => 'z0cken',
        'description' => 'Multiplayer Projekt von pr0gramm',
      ],
      [
        'url' => 'https://discord.gg/pr0',
        'thumb' => 'discord',
        'name' => 'Discord',
        'author' => 'pr0gramm',
        'description' => 'Der offizielle pr0gramm Discordserver',
      ],
      [
        'url' => 'https://discord.gg/mpJ6YYGzBq',
        'thumb' => 'pr0grammierer',
        'name' => 'pr0grammierer Discord',
        'author' => 'pr0gramm',
        'description' => 'Der offizielle pr0gramm Entwickler Discordserver',
      ],
      [
        'url' => 'https://pr0gramm.com/search',
        'thumb' => 'erweiterteSuche',
        'name' => 'Erweiterte Suche',
        'author' => 'pr0gramm',
        'description' => 'Die erweiterte Suche für noch bessere Suchergebnisse',
      ],
      [
        'url' => 'https://pr0gramm.com/new/3323910',
        'thumb' => 'rueckwaertssuche',
        'name' => 'Rückwärtssuche',
        'author' => 'pr0gramm',
        'description' => 'Der Infopost zur Rückwärtssuche auf pr0gramm',
      ],
      [
        'url' => 'https://github.com/pr0gramm-com/api-docs',
        'thumb' => 'apiDocs',
        'name' => 'API-Dokumentation',
        'author' => 'pr0gramm',
        'description' => 'API Dokumentation für Entwickler',
      ],
    ],
  ],
  'scripts' => [
    'title' => 'Scripts & Addons',
    'symbol' => 'f121',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://scarwolf.github.io/p0weruser/p0weruser.user.js',
        'thumb' => 'p0weruser',
        'name' => 'p0weruser Userscript',
        'author' => 'PoTTii',
        'description' => 'Root-Zugriff auf das pr0gramm! WideScreen Modus, Notification Center, eingefärbte Kommentar-Ebenen, uvm.',
      ],
      [
        'url' => 'https://pr0gramm.com/new/3145896',
        'thumb' => 'fitImages',
        'name' => 'Bilder Scaling Userscript',
        'author' => 'findus',
        'description' => 'Passt auf Tastendruck die Höhe des angezeigten Bildes an und macht es so möglich erwas höhere Bilder auf kleineren Monitoren zu anzuschauen ohne zu scrollen',
      ],
      [
        'url' => 'https://pr0gramm.com/new/3568968',
        'thumb' => 'sch0ngesehen',
        'name' => 'sch0ngesehen',
        'author' => 'Mwni',
        'description' => 'Ein Browseraddon um anzuzeigen, welche Posts man bereits gesehen hat',
      ],
      [
        'url' => 'https://addons.mozilla.org/de/firefox/collections/17356040/pr0-Themes/',
        'thumb' => 'themes',
        'name' => 'Themes für Firefox',
        'author' => 'J4it',
        'description' => 'Firefox Themes in den bewährten pr0gramm Farben',
      ],
      [
        'url' => 'https://napoii.github.io/pr0-score-plus/pr0-score-plus.user.js',
        'thumb' => 'pr0-score-plus',
        'name' => 'pr0-score-plus',
        'author' => 'NapoII',
        'description' => 'Zeigt BENIS, BLUSSIS, MINUS, Aktionen & Punktzahl mit Tortendiagramm. Klick kopiert Werte ins Clipboard',
      ],
      [
        'url' => 'https://greasyfork.org/en/scripts/550032-pr0gramm-keybindings-remapper',
        'thumb' => 'pr0-keybindings-remapper',
        'name' => 'Keybindings Remapper',
        'author' => 'tecoguy',
        'description' => 'Userscript für Tampermonkey o.ä. um Keybindings auf pr0gramm zu ändern.',
      ],
      [
        'url' => 'https://github.com/pr0-dev/pr0-tv',
        'thumb' => 'pr0tv',
        'name' => 'pr0-TV',
        'author' => 'TheShad0w',
        'description' => 'Das Userscript bringt pr0-TV als Feature zurück!',
      ],
    ],
  ],
  'community' => [
    'title' => 'Communityprojekte',
    'symbol' => 'f552',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://pr0p0ll.com/',
        'thumb' => 'pr0p0ll',
        'name' => 'pr0p0ll',
        'author' => 'PimmelmannJones',
        'description' => 'Stelle den Usern des pr0gramms ein paar Fragen!',
      ],
      [
        'url' => 'http://badewannencalculator.de/',
        'thumb' => 'badewannencalculator',
        'name' => 'BadewannenCalculator',
        'author' => 'ufop',
        'description' => 'Der praktische Rechner zum Umrechnen gemäß pr0-Norm 1',
      ],
    ],
  ],
  'bots' => [
    'title' => 'Nutzer-Bots',
    'symbol' => 'f544',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://pr0gramm.com/new/5376709',
        'thumb' => 'vergissmichnicht',
        'name' => '@vergissmichnicht',
        'author' => 'AlfonsoHater',
        'description' => 'Erinnerungsbot für automatische Erinnerungen per PN',
      ],
      [
        'url' => 'https://pr0gramm.com/new/4625113',
        'thumb' => 'sauce',
        'name' => '@Sauce',
        'author' => 'Helix',
        'description' => 'Erkennt Musik in Videos und postet Titel und Interpret',
      ],
      [
        'url' => 'https://pr0gramm.com/new/5783149',
        'thumb' => 'tldr',
        'name' => '@tldr',
        'author' => 'PimmelmannJones',
        'description' => 'Zusammenfassung eines vorstehenden Textes',
      ],
      [
        'url' => 'https://pr0gramm.com/new/5784369',
        'thumb' => 'linkers',
        'name' => '@linkers',
        'author' => 'Kavatch',
        'description' => 'Entfernung lästiger Tracking Parameter in Links',
      ],
    ],
  ],
  'apps' => [
    'title' => 'Apps',
    'symbol' => 'f3cd',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://app.pr0gramm.com/',
        'thumb' => 'app',
        'name' => 'pr0gramm Android App',
        'author' => 'Mopsalarm',
        'description' => 'Die offizielle pr0gramm Android App',
      ],
      [
        'url' => 'https://github.com/daranto/Pr0gramm-Client-IOS-MacOS',
        'thumb' => 'iOSApp',
        'name' => 'iOS & macOS App',
        'author' => 'Daranto',
        'description' => 'Inoffizielle iOS & macOS pr0gramm App',
      ],
    ],
  ],
  'stats' => [
    'title' => 'Statistiken',
    'symbol' => 'f00b',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://pr0gramm.com/user/DerpyDerp/uploads/w0chenstatistik',
        'thumb' => 'w0chenstatistik',
        'name' => 'w0chenstatistik',
        'author' => 'DerpyDerp',
        'description' => "Die Wochenstatistik.\nImmer Montags um 21:00 Uhr.",
      ],
      [
        'url' => 'https://pr0stats.github.io/',
        'thumb' => 'pr0stats',
        'name' => 'pr0stats (veraltet)',
        'author' => 'pr0stats',
        'description' => 'Alte Statistiken über das pr0gramm.',
      ],
    ],
  ],
  'niceToKnow' => [
    'title' => 'Gut zu wissen',
    'symbol' => 'f0eb',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://pr0gramm.com/new/1350989',
        'thumb' => 'badewanne',
        'name' => 'pr0-Norm #1 - Die Badewanne',
        'author' => 'J0unz',
        'description' => 'Die allseits beliebte Badewanne genormt.',
      ],
      [
        'url' => 'https://pr0gramm.com/new/4239894',
        'thumb' => 'badewanne_1-2',
        'name' => 'pr0-Norm #1.2 - Aktualisierung',
        'author' => 'DerAckrige',
        'description' => 'Eine erneute Aktualisierung der Badenwannennorm.',
      ],
      [
        'url' => 'https://pr0gramm.com/new/4372488:comment45601148',
        'thumb' => '1typ',
        'name' => '1-Typ Stickerpack',
        'author' => 'Fehlgeburt',
        'description' => 'Die beliebten 1Typ Bilder als Stickerpack für Telegram, WhatsApp & Signal. (Siehe Kommentarbaum)',
      ],
      [
        'url' => 'https://pr0badges.github.io/',
        'thumb' => 'pr0badges',
        'name' => 'Badges',
        'author' => 'Blood32',
        'description' => 'Übersicht aller Badges auf pr0gramm.',
      ],
      [
        'url' => 'https://pr0gramm.com/new/1500962',
        'thumb' => 'gangsign',
        'name' => 'Gangsign 2.0',
        'author' => 'l00tSpastille',
        'description' => 'Das pr0-Gangsign wie es sein sollte.',
      ],
      [
        'url' => 'https://pr0gramm.com/new/1579819',
        'thumb' => 'screenshots',
        'name' => 'große, lange Screenshots',
        'author' => 'Donnerstaender',
        'description' => 'Tutorial um große, lange Screenshots zu erstellen.',
      ],
      [
        'url' => 'https://pr0gramm.com/new/1755191',
        'thumb' => 'tierduden',
        'name' => 'Tierduden v4',
        'author' => 'Unbefriedigend',
        'description' => 'Der pr0gramm Tierduden ist eine Aufstellung aller Kadsen, Kefer und .EXEn',
      ],
    ],
  ],
  'games' => [
    'title' => 'Spiele',
    'symbol' => 'f11b',
    'fa' => 'fas',
    'items' => [
      [
        'url' => 'https://z0cken.com/',
        'thumb' => 'z0cken',
        'name' => 'z0cken.com',
        'author' => 'z0cken',
        'description' => 'Multiplayer Projekt von pr0gramm',
      ],
      [
        'url' => 'https://pr0game.com/',
        'thumb' => 'pr0game',
        'name' => 'pr0game',
        'author' => 'Rosenreeman',
        'description' => '"OGame" Klon ohne Premiumfunktionen',
      ],
      [
        'url' => 'https://pr0gramm.com/new/2230627',
        'thumb' => 'flatterfogel',
        'name' => 'Flatterfogel',
        'author' => 'C0dingschmuser',
        'description' => 'Ein Flappybird-Klon als pr0-Version',
      ],
      [
        'url' => 'https://pr0gramm.com/new/3877042',
        'thumb' => 'pr0ball-2_0',
        'name' => 'pr0ball 2.0',
        'author' => 'Mopsi91',
        'description' => 'Sammelt Blussis, verzockt sie im Benitrat0r, verbessert eure Bälle und benutzt Skills um eure Gegner umzunieten',
      ],
      [
        'url' => 'https://pr0gramm.com/new/2561200',
        'thumb' => 'pr0fense',
        'name' => 'Pr0fense',
        'author' => 'C0dingschmuser',
        'description' => 'Tower-Defense Spiel im pr0gramm-Stil',
      ],
      [
        'url' => 'https://pr0gramm.com/new/3839649',
        'thumb' => 'pr0rona',
        'name' => 'pr0rona',
        'author' => 'pr0nihilo',
        'description' => 'Weiche geschickt den Viren aus, trinke Bier und erreiche deinen Hochwert',
      ],
      [
        'url' => 'https://pr0gramm.com/new/3126416',
        'thumb' => 'guess-the-tag',
        'name' => 'GuessTheTag',
        'author' => 'C0dingschmuser',
        'description' => 'Tag-Ratespiel, bei dem man von einem Post den korrekten Tag erraten muss',
      ],
    ],
  ],
];
?>
